//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EpiasRest.Messager {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseResult", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(EpiasRest.Messager.SmsResult))]
    public partial class BaseResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EpiasRest.Messager.Message ResultField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public EpiasRest.Messager.Message Result {
            get {
                return this.ResultField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultField, value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Message", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Message : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResultTypeField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InfoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ResultType {
            get {
                return this.ResultTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultTypeField, value) != true)) {
                    this.ResultTypeField = value;
                    this.RaisePropertyChanged("ResultType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Info {
            get {
                return this.InfoField;
            }
            set {
                if ((object.ReferenceEquals(this.InfoField, value) != true)) {
                    this.InfoField = value;
                    this.RaisePropertyChanged("Info");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SmsResult", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class SmsResult : EpiasRest.Messager.BaseResult {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EpiasRest.Messager.SmsResponse[] ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public EpiasRest.Messager.SmsResponse[] Value {
            get {
                return this.ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueField, value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SmsResponse", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class SmsResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InfoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContentField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ID {
            get {
                return this.IDField;
            }
            set {
                if ((object.ReferenceEquals(this.IDField, value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Phone {
            get {
                return this.PhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneField, value) != true)) {
                    this.PhoneField = value;
                    this.RaisePropertyChanged("Phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Info {
            get {
                return this.InfoField;
            }
            set {
                if ((object.ReferenceEquals(this.InfoField, value) != true)) {
                    this.InfoField = value;
                    this.RaisePropertyChanged("Info");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Content {
            get {
                return this.ContentField;
            }
            set {
                if ((object.ReferenceEquals(this.ContentField, value) != true)) {
                    this.ContentField = value;
                    this.RaisePropertyChanged("Content");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Messager.MessagerSoap")]
    public interface MessagerSoap {
        
        // CODEGEN: Generating message contract since element name SessionId from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendSmsById", ReplyAction="*")]
        EpiasRest.Messager.SendSmsByIdResponse SendSmsById(EpiasRest.Messager.SendSmsByIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendSmsById", ReplyAction="*")]
        System.Threading.Tasks.Task<EpiasRest.Messager.SendSmsByIdResponse> SendSmsByIdAsync(EpiasRest.Messager.SendSmsByIdRequest request);
        
        // CODEGEN: Generating message contract since element name SessionId from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendSms", ReplyAction="*")]
        EpiasRest.Messager.SendSmsResponse SendSms(EpiasRest.Messager.SendSmsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendSms", ReplyAction="*")]
        System.Threading.Tasks.Task<EpiasRest.Messager.SendSmsResponse> SendSmsAsync(EpiasRest.Messager.SendSmsRequest request);
        
        // CODEGEN: Generating message contract since element name SessionId from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QuerySms", ReplyAction="*")]
        EpiasRest.Messager.QuerySmsResponse QuerySms(EpiasRest.Messager.QuerySmsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QuerySms", ReplyAction="*")]
        System.Threading.Tasks.Task<EpiasRest.Messager.QuerySmsResponse> QuerySmsAsync(EpiasRest.Messager.QuerySmsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendSmsByIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendSmsById", Namespace="http://tempuri.org/", Order=0)]
        public EpiasRest.Messager.SendSmsByIdRequestBody Body;
        
        public SendSmsByIdRequest() {
        }
        
        public SendSmsByIdRequest(EpiasRest.Messager.SendSmsByIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendSmsByIdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SessionId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int SmsId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Content;
        
        public SendSmsByIdRequestBody() {
        }
        
        public SendSmsByIdRequestBody(string SessionId, int SmsId, string Content) {
            this.SessionId = SessionId;
            this.SmsId = SmsId;
            this.Content = Content;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendSmsByIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendSmsByIdResponse", Namespace="http://tempuri.org/", Order=0)]
        public EpiasRest.Messager.SendSmsByIdResponseBody Body;
        
        public SendSmsByIdResponse() {
        }
        
        public SendSmsByIdResponse(EpiasRest.Messager.SendSmsByIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendSmsByIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public EpiasRest.Messager.SmsResult SendSmsByIdResult;
        
        public SendSmsByIdResponseBody() {
        }
        
        public SendSmsByIdResponseBody(EpiasRest.Messager.SmsResult SendSmsByIdResult) {
            this.SendSmsByIdResult = SendSmsByIdResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendSmsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendSms", Namespace="http://tempuri.org/", Order=0)]
        public EpiasRest.Messager.SendSmsRequestBody Body;
        
        public SendSmsRequest() {
        }
        
        public SendSmsRequest(EpiasRest.Messager.SendSmsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendSmsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SessionId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int SmsId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Recipients;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Content;
        
        public SendSmsRequestBody() {
        }
        
        public SendSmsRequestBody(string SessionId, int SmsId, string Recipients, string Content) {
            this.SessionId = SessionId;
            this.SmsId = SmsId;
            this.Recipients = Recipients;
            this.Content = Content;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendSmsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendSmsResponse", Namespace="http://tempuri.org/", Order=0)]
        public EpiasRest.Messager.SendSmsResponseBody Body;
        
        public SendSmsResponse() {
        }
        
        public SendSmsResponse(EpiasRest.Messager.SendSmsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendSmsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public EpiasRest.Messager.SmsResult SendSmsResult;
        
        public SendSmsResponseBody() {
        }
        
        public SendSmsResponseBody(EpiasRest.Messager.SmsResult SendSmsResult) {
            this.SendSmsResult = SendSmsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class QuerySmsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="QuerySms", Namespace="http://tempuri.org/", Order=0)]
        public EpiasRest.Messager.QuerySmsRequestBody Body;
        
        public QuerySmsRequest() {
        }
        
        public QuerySmsRequest(EpiasRest.Messager.QuerySmsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class QuerySmsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SessionId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string SmsID;
        
        public QuerySmsRequestBody() {
        }
        
        public QuerySmsRequestBody(string SessionId, string SmsID) {
            this.SessionId = SessionId;
            this.SmsID = SmsID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class QuerySmsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="QuerySmsResponse", Namespace="http://tempuri.org/", Order=0)]
        public EpiasRest.Messager.QuerySmsResponseBody Body;
        
        public QuerySmsResponse() {
        }
        
        public QuerySmsResponse(EpiasRest.Messager.QuerySmsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class QuerySmsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public EpiasRest.Messager.SmsResult QuerySmsResult;
        
        public QuerySmsResponseBody() {
        }
        
        public QuerySmsResponseBody(EpiasRest.Messager.SmsResult QuerySmsResult) {
            this.QuerySmsResult = QuerySmsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MessagerSoapChannel : EpiasRest.Messager.MessagerSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MessagerSoapClient : System.ServiceModel.ClientBase<EpiasRest.Messager.MessagerSoap>, EpiasRest.Messager.MessagerSoap {
        
        public MessagerSoapClient() {
        }
        
        public MessagerSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MessagerSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MessagerSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MessagerSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EpiasRest.Messager.SendSmsByIdResponse EpiasRest.Messager.MessagerSoap.SendSmsById(EpiasRest.Messager.SendSmsByIdRequest request) {
            return base.Channel.SendSmsById(request);
        }
        
        public EpiasRest.Messager.SmsResult SendSmsById(string SessionId, int SmsId, string Content) {
            EpiasRest.Messager.SendSmsByIdRequest inValue = new EpiasRest.Messager.SendSmsByIdRequest();
            inValue.Body = new EpiasRest.Messager.SendSmsByIdRequestBody();
            inValue.Body.SessionId = SessionId;
            inValue.Body.SmsId = SmsId;
            inValue.Body.Content = Content;
            EpiasRest.Messager.SendSmsByIdResponse retVal = ((EpiasRest.Messager.MessagerSoap)(this)).SendSmsById(inValue);
            return retVal.Body.SendSmsByIdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EpiasRest.Messager.SendSmsByIdResponse> EpiasRest.Messager.MessagerSoap.SendSmsByIdAsync(EpiasRest.Messager.SendSmsByIdRequest request) {
            return base.Channel.SendSmsByIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<EpiasRest.Messager.SendSmsByIdResponse> SendSmsByIdAsync(string SessionId, int SmsId, string Content) {
            EpiasRest.Messager.SendSmsByIdRequest inValue = new EpiasRest.Messager.SendSmsByIdRequest();
            inValue.Body = new EpiasRest.Messager.SendSmsByIdRequestBody();
            inValue.Body.SessionId = SessionId;
            inValue.Body.SmsId = SmsId;
            inValue.Body.Content = Content;
            return ((EpiasRest.Messager.MessagerSoap)(this)).SendSmsByIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EpiasRest.Messager.SendSmsResponse EpiasRest.Messager.MessagerSoap.SendSms(EpiasRest.Messager.SendSmsRequest request) {
            return base.Channel.SendSms(request);
        }
        
        public EpiasRest.Messager.SmsResult SendSms(string SessionId, int SmsId, string Recipients, string Content) {
            EpiasRest.Messager.SendSmsRequest inValue = new EpiasRest.Messager.SendSmsRequest();
            inValue.Body = new EpiasRest.Messager.SendSmsRequestBody();
            inValue.Body.SessionId = SessionId;
            inValue.Body.SmsId = SmsId;
            inValue.Body.Recipients = Recipients;
            inValue.Body.Content = Content;
            EpiasRest.Messager.SendSmsResponse retVal = ((EpiasRest.Messager.MessagerSoap)(this)).SendSms(inValue);
            return retVal.Body.SendSmsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EpiasRest.Messager.SendSmsResponse> EpiasRest.Messager.MessagerSoap.SendSmsAsync(EpiasRest.Messager.SendSmsRequest request) {
            return base.Channel.SendSmsAsync(request);
        }
        
        public System.Threading.Tasks.Task<EpiasRest.Messager.SendSmsResponse> SendSmsAsync(string SessionId, int SmsId, string Recipients, string Content) {
            EpiasRest.Messager.SendSmsRequest inValue = new EpiasRest.Messager.SendSmsRequest();
            inValue.Body = new EpiasRest.Messager.SendSmsRequestBody();
            inValue.Body.SessionId = SessionId;
            inValue.Body.SmsId = SmsId;
            inValue.Body.Recipients = Recipients;
            inValue.Body.Content = Content;
            return ((EpiasRest.Messager.MessagerSoap)(this)).SendSmsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EpiasRest.Messager.QuerySmsResponse EpiasRest.Messager.MessagerSoap.QuerySms(EpiasRest.Messager.QuerySmsRequest request) {
            return base.Channel.QuerySms(request);
        }
        
        public EpiasRest.Messager.SmsResult QuerySms(string SessionId, string SmsID) {
            EpiasRest.Messager.QuerySmsRequest inValue = new EpiasRest.Messager.QuerySmsRequest();
            inValue.Body = new EpiasRest.Messager.QuerySmsRequestBody();
            inValue.Body.SessionId = SessionId;
            inValue.Body.SmsID = SmsID;
            EpiasRest.Messager.QuerySmsResponse retVal = ((EpiasRest.Messager.MessagerSoap)(this)).QuerySms(inValue);
            return retVal.Body.QuerySmsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EpiasRest.Messager.QuerySmsResponse> EpiasRest.Messager.MessagerSoap.QuerySmsAsync(EpiasRest.Messager.QuerySmsRequest request) {
            return base.Channel.QuerySmsAsync(request);
        }
        
        public System.Threading.Tasks.Task<EpiasRest.Messager.QuerySmsResponse> QuerySmsAsync(string SessionId, string SmsID) {
            EpiasRest.Messager.QuerySmsRequest inValue = new EpiasRest.Messager.QuerySmsRequest();
            inValue.Body = new EpiasRest.Messager.QuerySmsRequestBody();
            inValue.Body.SessionId = SessionId;
            inValue.Body.SmsID = SmsID;
            return ((EpiasRest.Messager.MessagerSoap)(this)).QuerySmsAsync(inValue);
        }
    }
}
